### PR TITLE
Bump default max number of wiki pages to 50

### PR DESCRIPTION
**Pull request by lol768**
#272 

Will likely require a conf change for prod.

### CODE REVIEW

**Comment by simon816** [comment]
According to @NeumimTo on the forums (https://forums.spongepowered.org/t/wiki-pages/19838/8) the max page count is only verified client side, maybe you could add a check server side too.

**Comment by NeumimTo** [comment]
Yep thats correct. No validation in server's bussines logic.

**Comment by lol768** [comment]
Yeah, mbaxter mentioned that to me... Will add a server-side check

**Comment by lol768** [comment]
#284

**Review by kashike — APPROVED** [review]

**Pull request merged**
