### PR TITLE
Tag System

### PR DESCRIPTION
**Pull request by phase**
I'm starting to implement the system I described in #307. 

`isSpongePlugin` and `isForgeMod` have been converted into Tags.
Other Tags will exist later, but for now we only have Sponge and Forge Tags.

Each Project contains a Tags String, which will contain a comma-separated list of ints.
These ints refer to Tags in the `project_tags` table. These tags are project-specific, to make
it more extensible and because projects use different versions of the SpongeAPI/ForgeAPI.
The `project_tags` table consists of a `name`, `data`, and `color`. For API tags, the name
and color tags will be the same, and the data tag will refer to the version of the API.

The toughest part will be migrating the current database to fit this system. That's what `79.sql`
(or `80.sql` once #302 gets merged) will do. Currently, it's a mess of SQL code. IntelliJ doesn't
report any issues with it, but I still need to do some testing.

Reviews & comments are always welcome (someone should probably double check my SQL).
This will conflict with #302 once it is merged.

### CODE REVIEW

**Comment by phase** [comment]
Wait, storing a list of integers as a string is dumb. Let me fix that.

**Comment by phase** [comment]
The SQL for converting to the new system works! Now to do the reversion code.

**Comment by phase** [comment]
@Zerthick had the brilliant idea to make tags _per version_ instead of _per project_. Plugin Versions will use different API versions, and displaying what API works with what version will be helpful to users.

**Comment by Zerthick** [comment]
So this may be a given, but having a system to filter projects by the tags associated with their recommended version would also be very helpful, if for example I'm only interested in viewing plugins with a recommended version compatible with the version of sponge I am running. I think in that case #213 will probably need to be revisited as it makes sense that plugins my have a separate recommended build for each version of the API

**Comment by phase** [comment]
Filters will be added once the tags are in place. Filtering out WIP projects and versions you don't want will be useful. (#294)

**Comment by phase** [comment]
Now we're getting somewhere! Tags are _per version_. The SpongeAPI/ForgeAPI tags that are being added need to be reviewed, as the way I'm adding the Tags to the DB is weird. The regression SQL also still needs to be written.

**Comment by phase** [comment]
Next major rewrite I need to do is to allow tags to support _multiple_ versions.

Currently, each tag is linked to one project version. If we have 10 versions for 100 projects that are all using Sponge API 6.0.0, that's 1,000 rows in the DB instead of 1. This can be fixed by changing `version_id int` to `version_ids int []`.

**Comment by phase** [comment]
The last thing that needs to be written is the SQL regression.

**Comment by phase** [comment]
Tags migrate perfectly & the regression script is there if we want to revert it.
Filters still need to be done, but that can be done in another PR.

**Comment by phase** [comment]
This needs some testing. I already had @progwml6 run the big query script to create the tags, but I need to test some stuff with Forge still.

On the frontend, I want to have the tags be displayed within the versions list. Shouldn't be too difficult.

**Comment by phase** [comment]
I've tested everything with a copy of the prod DB and it works! :tada: :tada:

Sponge version tags will be displayed in the Projects version list:

example image

**Comment by phit** [comment]
maybe put the minecraft version in brackets? most random people may not necessarily know what api version targets what minecraft version

**Comment by phase** [comment]
I don't think I want to do MC versions in this PR. That can be put in place later, along with other tags. I just want to get the core Tags system in place.

Filtering is another big thing that needs to get completed, and sorting by Sponge/Forge/MC version will be in that system.

**Comment by phase** [comment]
This has conflicts with #316.

**Comment by phase** [comment]
WIP Tags are in! ~~Everything should be completed for this PR!~~ :tada: :tada: :tada: :tada:

wip

**Comment by phase** [comment]
Todo List:
 * [x] Displaying the RV's tags in the plugin list
 * [ ] Fix filtering

**Comment by phase** [comment]
I'm going to do filtering later. There's a lot that needs to be done and it isn't fit for this PR. For now the platform filter will display every project, which shouldn't be a big deal considering only 2 projects are Forge mods in the prod DB.

So I guess this is good to be merged! :tada: :tada: :tada: :tada:

home page

#307 can be closed when this is merged in.

**Review by kashike — APPROVED** [review]

**Review by felixoi — APPROVED** [review]
I can confirm that's working on my side.

**Comment by dualspiral** [comment]
Putting my user/UX hat on:

I have a question about the WIP tags - but this is more semantics and naming so this could rumble on later after this is merged if desired. I suspect "WIP" is only used because of our "WIP Plugins" forum category - the use case there is a new plugin that has yet to be fully released as a first version. Would WIP be appropriate for established plugins that aren't a work in progress, but want to provide pre-release versions? Should it be more general, something like "pre-release" or "unstable"? 

From a translation point of view, while it's obvious to many, particularly developers, what WIP means, I don't think it's universal, anyone using a translator would not necessarily get the acronym.

Looking at the function, there is a "WIP" checkbox, with no indication as to what it could do. I'd like to see the checkbox have a line of description with it, at least, that explains what that means. If it's left to say "WIP", it explains nothing to new developers. It's a checkbox with three letters. If it had a line that said "This marks this version as a 'work in progress'/'pre-release' and will warn users that the plugin is potentially unstable on download" or something, that gives understanding to the checkbox.

(Also, again, could be a simple addon later down the road, would it be worth adding an "unreviewed" tag for those plugins that have not been reviewed internally yet?)

**Comment by ryantheleach** [comment]
I think WIP should differ from a nightly or pre-release channel, in that it hides by default on the plugin browse / category pages, and only shows if you are looking for WIP plugins specifically.

That's the point of the WIP forums, to gauge interest for a project that may not even have downloads available yet, or may be abandoned before ever releasing, or just to show off stuff to gain interest and motivation.

At the moment Ore is incapable of creating a project without an initial upload(to my knowledge), factoring a WIP project to properly represent what the forum WIP section is will be somewhat painful.
 

Although, duals comment and mine probably should be on https://github.com/SpongePowered/Ore/issues/307

**Comment by phase** [comment]
@dualspiral
I like `unstable`. The WIP name came from #307 (~~so blame @Owexz~~).

Does `Mark this version as unstable` sound good?

We **need** user hats on. As a developer, I know exactly what _WIP_ means when I see it, but sometimes I'm not thinking in the mind of the average Minecraft player (I try my best, but sometimes it slips).

Other tags will come later. I don't want to add anything else to this PR.

@ryantheleach 
When I get filtering implemented, I'm planning on filtering the front page with WIP projects hidden by default.

If projects are on the WIP forum section _without a buildable version_ then I don't really know what they're doing there. Ore shouldn't be a place for _planning_ plugins, it should be a place for _releasing_ plugins. You can plan plugins on the forums. (And allowing projects to be created without a version would break _everything_ and that's a lot of code I don't want to touch.)


<br>

If anyone has any suggestions for colors let me know.

**Comment by ryantheleach** [comment]
That's fine, I just figured I would highlight a usecase of the forums that Ore can't fulfill easily.

**Comment by dualspiral** [comment]
> Does Mark this version as unstable sound good?

Yes, that's clearer. I still think there needs to be a description somewhere as to what "unstable" means on Ore, such as are they hidden by default, for example (as you suggest) - but I think the function above and beyond a tag is outside the scope of this PR, as correctly noted.

**Comment by phase** [comment]
`WIP` Tags are now `Unstable`.
  Any other suggestions?

**Comment by phase** [comment]
:tada:

**Pull request merged**
