### PR TITLE
Clarify IntelliJ setup details.

### PR DESCRIPTION
**Pull request by JBYoshi**
I run IntelliJ Community Edition, so this didn't work for me. :stuck_out_tongue_closed_eyes:

### CODE REVIEW

**Comment by Flibio** [comment]
Maybe include specific instructions for the Community Edition?

**Comment by JBYoshi** [comment]
@Flibio Unfortunately, there aren't any for it. I changed the ordering a bit to clarify that.

**Comment by windy1** [comment]
Hmm well yeah while you can't run it right in IntelliJ CE you can still develop with it and run it in the background. Auto-refreshing should work as well.

**Comment by JBYoshi** [comment]
Yep. I was planning to do just that.

**Pull request merged**
