### PR TITLE
Add staff page

### PR DESCRIPTION
**Pull request by Katrix**
Adds the staff page. Need a better icon than the base user icon. Tried to unify some of the code that was shared with the authors endpoint.

### CODE REVIEW

**Review by phase — APPROVED** [review]
what's here LGTM, waiting on icon for nav

**Comment by Ewoutvans** [comment]
Screenshot for those who don't want to run it:
schermafbeelding 2018-04-18 om 07 49 46

**Comment by mbax** [comment]
Cute!

**Comment by phase** [comment]
What's the status on an icon for this? Can we throw some font awesome icon in there?

**Review by phase — APPROVED** [review]

**Pull request merged**
