### PR TITLE
Add WikiLinks, Add duplicate pages

### LINKED ISSUE #421: Cannot name two pages with the same heading
When adding a new page as a sub page, it cannot have the same name as another page that is a parent page.

Steps to reproduce:

* Step 1 Add a parent page, say, `Modules`
* Step 2 To that parent page, add `Home`

You'll get the editor for the `Home` page, when you wanted a new page under `Modules/Home`

### PR DESCRIPTION
**Pull request by Ewoutvans**
- Update Flexmark from 0.18.2 --> 0.32.4
- Add WikiLinks `[[Command]]` will guarantee an always working absolute link
- Add `/pages/:parent/:child` use `[[Commands/Admin]]` to get a working link
- Add duplicate Page names (needs some more testing) if not in the same root so 
       you can have 1 `Admin`-page in Commands and 1 `Admin`-page in root but not 2 `Admin`-pages in root

This fixes #421 and #265 

Example:
schermafbeelding 2018-02-21 om 19 12 13

### CODE REVIEW

**Comment by dualspiral** [comment]
> Add WikiLinks [[Command]] will guarantee an always working absolute link

Will that work on the home page that gets mirrored to Discourse - that is, will this syntax work on the forum post Ore generates, or would that not get parsed by Discourse?

**Review by felixoi — APPROVED** [review]

**Comment by progwml6** [comment]
Before merging, and behavior changes/additions will need to be documented so that users can understand the new behavior, and how it differs from what currently exists, and what backwards compatibility exists now, and what we plan to remove long term.

**Comment by phase** [comment]
Discourse links need to be handled.

**Comment by felixoi** [comment]
Copied from @progwml6 on discord:
> Just leave the links in these as is for now and file an issue to fix them later

**Pull request merged**
