### PR TITLE
Reworked footer

### PR DESCRIPTION
**Pull request by felixoi**
preview

### CODE REVIEW

**Comment by phase** [comment]
Can you post a screenshot with it in context with the rest of the site?

I like where this is going, but I think we're missing some key links like the TOS (which is currently being written) and the support forum.

**Comment by felixoi** [comment]
@phase 

preview

And I can add the TOS when it's done. Support Forum is under "Help needed"

**Comment by phit** [comment]
REST is an acronym that should be fully capitalized. So either "Ore REST API" or personally I think just "API" would be enough, since you are on the Ore site anyway and it doesn't really matter to the devs (at least for this link) that would click on this what kind of API it is.

**Comment by phase** [comment]
I personally think it might be a little too big. We don't want it to distract from the plugin list.

**Comment by felixoi** [comment]
@phit should be fixed now. Look in the initial comment.
@phase Changed button label to "Support Forum" to make it more clear.

Moreover, the footer has to be "so big" if you wanna display the information nicely. It will not distract from the plugin list, since on Ore Production the list is much longer and the footer will be pushed down.

**Comment by felixoi** [comment]
Added ToS placeholder. Should be ready to merge.

**Review by phase — APPROVED** [review]

**Pull request merged**
