### PR TITLE
Github-style deletes

### PR DESCRIPTION
**Pull request by connor4312**
I always liked how Github deletes repos. Implemented similar functionality in Ore.

### CODE REVIEW

**Comment by JustinHarper** [comment]
Hope this gets merged. :+1:

**Comment by gratimax** [comment]
Is there any chance to move this into Django form validation? Or is the instant feedback provided by writing this in Javascript essential? I guess once that's answered, it would be nice to have the same thing for renames (adding the same project name confirmation).

**Comment by connor4312** [comment]
It's instant feedback. I don't think there's a need to move this into Django - we don't really care about the integrity here, it's just to provide something a little more "conscious" for the average user than simply a big read button.

As far as renames... those aren't destructive actions, so I'm not sure that they need a confirmation. You also already have to type out the new name of the repo, so I would say that's probably sufficient interaction that an additional confirmation isn't necessary.

**Comment by gratimax** [comment]
Fair enough. Thanks, :+1: and merge

**Comment by ryantheleach** [comment]
In regards to renames it depends if you implement any sort of approval or cool down on renames of projects. If people can rename unlimited amount of times there is no real need (apart from it causing any links from anywhere to break..)

**Comment by simon816** [comment]
As added protection it could ask for the user's password too.

**Comment by gratimax** [comment]
I have been considering something like GitHub's "sudo-mode", but it seems like unnecessary work at this point and is more like a "someday" feature.

**Pull request merged**
