### PR TITLE
Update from Raven to Sentry

### LINKED ISSUE #481: Update sentry client
Please update the sentry client using the folllowing migration guide
https://docs.sentry.io/clients/java/migration/

### PR DESCRIPTION
**Pull request by phase**
Closes #481

Signed-off-by: Jadon Fowler <jadonflower@gmail.com>

### CODE REVIEW

**Comment by felixoi** [comment]
Please set all loggers to warn. We don't need to get info messages on sentry.

**Comment by phase** [comment]
Loggers were changed.

**Comment by felixoi** [comment]
I get some stupid console messages, as well as info messages are now no longer shown up in development. They should only be logged when in production.

[My Log](https://gist.githubusercontent.com/felixoi/0caab64031487c8fce1dec98231440ef/raw/c62b12f7144d695ff577e3d9e3d8835a3294d799/sentry.log)

**Comment by felixoi** [comment]
I changed some things and re-opened this as #499 because you don't use branches in this repository.

**Pull request closed without merging**
