### PR TITLE
Style Improvements

### PR DESCRIPTION
**Pull request by Flibio**
Contains a few style improvements to Ore, including:
- Modified the brand color to a slightly darker shade, improving readability on the white background
- Changed the color of header to match other Sponge sites
- Removed the forums link from the user dropdown
- Converted the header logo image to a dropdown to match the other Sponge sites

### CODE REVIEW

**Comment by windy1** [comment]
Good stuff @Flibio! The only little nitpick I have is that the new dropdown doesn't match the width of the logo. Other than that this is great!

**Comment by Flibio** [comment]
Fixed that, and squashed the commits!

**Comment by windy1** [comment]
Oh whoops! I fixed it myself and merged it already lol.

**Comment by Flibio** [comment]
:smile: I also included this change in the final commit, could you add it? It makes the size of the icons in the dropdown the same because the Javadocs one was slightly bigger than all others.

``` css
.main-dropdown li .fa {
    margin-right: 10px;
    min-width: 18px; /**<--This line right here**/
}
```

**Comment by windy1** [comment]
No prob. It'll be in the next commit.

**Pull request closed without merging**
