### PR TITLE
Ignore local config files

### PR DESCRIPTION
**Pull request by connor4312**
Was poking around and noticed this. Having config files tracked in vcs is a great way to accidentally commit passwords or just screw up other developers' setups if you accidentally commit a change!

Probably a good idea to get a setup.py going with disutils that takes care of install dependencies, ensure prereqs are present, and perhaps copies example.* without the "example" part for easy development from the get-go.

### CODE REVIEW

**Comment by lukegb** [comment]
You're missing the point of this, I feel.

The settings are set up like this on purpose - if you absolutely need to overlay local settings, ore/settings/local.py is explicitly ignored, but in general everyone should be running with the same settings - it means that bugs experienced in production are less likely to be hidden by minor configuration details. Obviously things like the actual database credentials and some debugging utilities will be different, but these changes are clearly documented for everyone to see in source control - you shouldn't /have/ to make any changes locally, if you see what I mean.

If you have a good reason why you think this is bad, please do reply to this ticket, but for now I'm going to close it out.

**Comment by connor4312** [comment]
For that to work, developers will have to have the same exact environments... which can be done using a tool like Vagrant. I know you have Docker there, but that's not really build for development, and it doesn't work natively on Windows. I'd suggest getting a Vagrant setup going. Vagrant can pull Docker containers as well: https://docs.vagrantup.com/v2/provisioning/docker.html

**Comment by lukegb** [comment]
At present, the most that will vary are the credentials, and possibly the hostname of, the database.

If needed, these can be overridden by making your own local.py (which would just start with `from .development import *` and then set `DATABASES`) and setting `ore.settings.local` as your `DJANGO_SETTINGS_MODULE`.

**Comment by connor4312** [comment]
I dislike the idea of requiring knowledge of the language an application is coded in in order to (properly) do basic configuration on it.

**Comment by gratimax** [comment]
I think we're talking about a lot of different things in this single PR:

> Was poking around and noticed this. Having config files tracked in vcs is a great way to accidentally commit passwords or just screw up other developers' setups if you accidentally commit a change!

I think luke pretty much covered this. ore/settings/local.py is ignored from version control, so it is encouraged to use that. Maybe adding a development guide to the readme would be a good idea so people understand how to configure their local environment.

> Probably a good idea to get a setup.py going with disutils that takes care of install dependencies, ensure prereqs are present, and perhaps copies example.* without the "example" part for easy development from the get-go.

That sounds like a solid idea, a separate PR would be great(or when I find the time, I can do it myself).

> I'd suggest getting a Vagrant setup going.

I have nothing against that either, but I think that Vagrantfiles are [supposed to be tracked in version control](https://github.com/discourse/discourse/blob/master/Vagrantfile). I don't have much experience with Vagrant in this setting, so feel free to correct me.

> I dislike the idea of requiring knowledge of the language an application is coded in in order to (properly) do basic configuration on it.

This is a different problem from the one this PR solves. If we wish to solve that, we could externalize the config into some system of files(for instance, using [configparser](https://docs.python.org/2/library/configparser.html) from the standard library). But that seems like a later-on feature to make deployment easier for sysadmins who do not speak Python.

**Pull request closed without merging**
