### PR TITLE
Minor url fixes.

### LINKED ISSUE #40: 500 Error when uploading a version
When I try to upload a version, I get a Server Error 500.

### LINKED ISSUE #41: 500 Error when deleting a project
When I try to delete a project, I get a Server Error 500.

### PR DESCRIPTION
**Pull request by sgtbigman**
- Fixes #40 and #41.

### CODE REVIEW

**Comment by sgtbigman** [comment]
If I stumble upon anymore, I'll let you know.

**Comment by gratimax** [comment]
:+1: Looks great, I just want to try and fix sentry reporting before I merge this so we can confirm both that the errors have stopped and that sentry works

**Comment by sgtbigman** [comment]
Sounds good.

Thanks for looking this over.

**Comment by gratimax** [comment]
Got sentry to work again!

sentry working

Going to merge, thanks again for the fixes.

**Pull request merged**
